services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    restart: always
  localstack:
    image: localstack/localstack:3.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
  init-queue:
    image: localstack/localstack:3.3
    entrypoint: ["/bin/sh", "/init-queue.sh"]
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    depends_on:
      - localstack
    volumes:
      - ./infra/init-queue.sh:/init-queue.sh
  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
      - localstack
      - init-queue

  worker:
    build: .
    command: python processor/worker.py
    volumes:
      - ./src:/app/src
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - SQS_ENDPOINT=http://localstack:4566
    depends_on:
      - mongo
      - localstack
      - init-queue